import {Employee} from './employee';

const defaultEmployees = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@emp.com',
    hireDate: new Date('2023-01-15'),
    dismissalDate: null,
    department: 'engineering',
    salary: 50000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '2',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@emp.com',
    hireDate: new Date('2023-02-20'),
    dismissalDate: null,
    department: 'finance',
    salary: 55000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '3',
    firstName: 'Emily',
    lastName: 'Jones',
    email: 'emily.jones@emp.com',
    hireDate: new Date('2023-03-10'),
    dismissalDate: null,
    department: 'customer success',
    salary: 60000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '4',
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@emp.com',
    hireDate: new Date('2023-04-25'),
    dismissalDate: null,
    department: 'engineering',
    salary: 65000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'superadmin',
  },
  {
    id: '5',
    firstName: 'Linda',
    lastName: 'Wilson',
    email: 'linda.wilson@emp.com',
    hireDate: new Date('2023-05-30'),
    dismissalDate: new Date('2023-12-31'),
    department: 'finance',
    salary: 70000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '6',
    firstName: 'David',
    lastName: 'Johnson',
    email: 'david.johnson@emp.com',
    hireDate: new Date('2023-06-15'),
    dismissalDate: null,
    department: 'engineering',
    salary: 55000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '7',
    firstName: 'Sarah',
    lastName: 'Anderson',
    email: 'sarah.anderson@emp.com',
    hireDate: new Date('2023-07-20'),
    dismissalDate: null,
    department: 'finance',
    salary: 60000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '8',
    firstName: 'Daniel',
    lastName: 'Martinez',
    email: 'daniel.martinez@emp.com',
    hireDate: new Date('2023-08-10'),
    dismissalDate: null,
    department: 'customer success',
    salary: 65000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '9',
    firstName: 'Jessica',
    lastName: 'Taylor',
    email: 'jessica.taylor@emp.com',
    hireDate: new Date('2023-09-25'),
    dismissalDate: null,
    department: 'engineering',
    salary: 70000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'superadmin',
  },
  {
    id: '10',
    firstName: 'Matthew',
    lastName: 'Walker',
    email: 'matthew.walker@emp.com',
    hireDate: new Date('2023-10-30'),
    dismissalDate: new Date('2023-12-31'),
    department: 'finance',
    salary: 75000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '11',
    firstName: 'Alex',
    lastName: 'Wilson',
    email: 'alex.wilson@emp.com',
    hireDate: new Date('2023-11-15'),
    dismissalDate: null,
    department: 'engineering',
    salary: 80000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '12',
    firstName: 'Olivia',
    lastName: 'Davis',
    email: 'olivia.davis@emp.com',
    hireDate: new Date('2023-12-20'),
    dismissalDate: null,
    department: 'finance',
    salary: 85000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '13',
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'robert.johnson@emp.com',
    hireDate: new Date('2023-01-05'),
    dismissalDate: null,
    department: 'engineering',
    salary: 60000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '14',
    firstName: 'Sophia',
    lastName: 'Brown',
    email: 'sophia.brown@emp.com',
    hireDate: new Date('2023-02-10'),
    dismissalDate: null,
    department: 'finance',
    salary: 65000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '15',
    firstName: 'William',
    lastName: 'Smith',
    email: 'william.smith@emp.com',
    hireDate: new Date('2023-03-25'),
    dismissalDate: null,
    department: 'customer success',
    salary: 70000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '16',
    firstName: 'Ava',
    lastName: 'Johnson',
    email: 'ava.johnson@emp.com',
    hireDate: new Date('2023-04-30'),
    dismissalDate: null,
    department: 'engineering',
    salary: 75000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'superadmin',
  },
  {
    id: '17',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@emp.com',
    hireDate: new Date('2023-05-15'),
    dismissalDate: new Date('2023-12-31'),
    department: 'finance',
    salary: 80000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '18',
    firstName: 'Mia',
    lastName: 'Davis',
    email: 'mia.davis@emp.com',
    hireDate: new Date('2023-06-20'),
    dismissalDate: null,
    department: 'engineering',
    salary: 85000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '19',
    firstName: 'Benjamin',
    lastName: 'Anderson',
    email: 'benjamin.anderson@emp.com',
    hireDate: new Date('2023-07-10'),
    dismissalDate: null,
    department: 'finance',
    salary: 90000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '20',
    firstName: 'Charlotte',
    lastName: 'Martinez',
    email: 'charlotte.martinez@emp.com',
    hireDate: new Date('2023-08-25'),
    dismissalDate: null,
    department: 'customer success',
    salary: 95000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '21',
    firstName: 'Henry',
    lastName: 'Taylor',
    email: 'henry.taylor@emp.com',
    hireDate: new Date('2023-09-30'),
    dismissalDate: null,
    department: 'engineering',
    salary: 100000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'superadmin',
  },
  {
    id: '22',
    firstName: 'Amelia',
    lastName: 'Walker',
    email: 'amelia.walker@emp.com',
    hireDate: new Date('2023-10-15'),
    dismissalDate: null,
    department: 'finance',
    salary: 105000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '23',
    firstName: 'Daniel',
    lastName: 'Wilson',
    email: 'daniel.wilson@emp.com',
    hireDate: new Date('2023-11-20'),
    dismissalDate: null,
    department: 'engineering',
    salary: 110000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '24',
    firstName: 'Evelyn',
    lastName: 'Davis',
    email: 'evelyn.davis@emp.com',
    hireDate: new Date('2023-12-10'),
    dismissalDate: null,
    department: 'finance',
    salary: 115000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '25',
    firstName: 'Oliver',
    lastName: 'Johnson',
    email: 'oliver.johnson@emp.com',
    hireDate: new Date('2023-01-01'),
    dismissalDate: null,
    department: 'engineering',
    salary: 60000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '26',
    firstName: 'Sophie',
    lastName: 'Brown',
    email: 'sophie.brown@emp.com',
    hireDate: new Date('2023-02-05'),
    dismissalDate: null,
    department: 'finance',
    salary: 65000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '27',
    firstName: 'Noah',
    lastName: 'Smith',
    email: 'noah.smith@emp.com',
    hireDate: new Date('2023-03-20'),
    dismissalDate: null,
    department: 'customer success',
    salary: 70000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '28',
    firstName: 'Emma',
    lastName: 'Johnson',
    email: 'emma.johnson@emp.com',
    hireDate: new Date('2023-04-15'),
    dismissalDate: null,
    department: 'engineering',
    salary: 75000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'superadmin',
  },
  {
    id: '29',
    firstName: 'Liam',
    lastName: 'Wilson',
    email: 'liam.wilson@emp.com',
    hireDate: new Date('2023-05-10'),
    dismissalDate: new Date('2023-12-31'),
    department: 'finance',
    salary: 80000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '30',
    firstName: 'Olivia',
    lastName: 'Davis',
    email: 'olivia.davis@emp.com',
    hireDate: new Date('2023-06-25'),
    dismissalDate: null,
    department: 'engineering',
    salary: 85000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '31',
    firstName: 'Lucas',
    lastName: 'Anderson',
    email: 'lucas.anderson@emp.com',
    hireDate: new Date('2023-07-20'),
    dismissalDate: null,
    department: 'finance',
    salary: 90000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '32',
    firstName: 'Ava',
    lastName: 'Martinez',
    email: 'ava.martinez@emp.com',
    hireDate: new Date('2023-08-15'),
    dismissalDate: null,
    department: 'customer success',
    salary: 95000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '33',
    firstName: 'Mason',
    lastName: 'Taylor',
    email: 'mason.taylor@emp.com',
    hireDate: new Date('2023-09-10'),
    dismissalDate: null,
    department: 'engineering',
    salary: 100000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'superadmin',
  },
  {
    id: '34',
    firstName: 'Isabella',
    lastName: 'Walker',
    email: 'isabella.walker@emp.com',
    hireDate: new Date('2023-10-05'),
    dismissalDate: null,
    department: 'finance',
    salary: 105000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '35',
    firstName: 'Ethan',
    lastName: 'Wilson',
    email: 'ethan.wilson@emp.com',
    hireDate: new Date('2020-11-30'),
    dismissalDate: null,
    department: 'engineering',
    salary: 110000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '36',
    firstName: 'Mia',
    lastName: 'Davis',
    email: 'mia.davis@emp.com',
    hireDate: new Date('2023-12-25'),
    dismissalDate: null,
    department: 'finance',
    salary: 115000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '37',
    firstName: 'Elijah',
    lastName: 'Johnson',
    email: 'elijah.johnson@emp.com',
    hireDate: new Date('2021-01-10'),
    dismissalDate: null,
    department: 'engineering',
    salary: 60000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '38',
    firstName: 'Scarlett',
    lastName: 'Brown',
    email: 'scarlett.brown@emp.com',
    hireDate: new Date('2020-02-15'),
    dismissalDate: null,
    department: 'finance',
    salary: 65000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '39',
    firstName: 'Logan',
    lastName: 'Smith',
    email: 'logan.smith@emp.com',
    hireDate: new Date('2013-03-20'),
    dismissalDate: null,
    department: 'customer success',
    salary: 70000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '40',
    firstName: 'Avery',
    lastName: 'Johnson',
    email: 'avery.johnson@emp.com',
    hireDate: new Date('2023-04-25'),
    dismissalDate: null,
    department: 'engineering',
    salary: 75000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'superadmin',
  },
  {
    id: '41',
    firstName: 'Ella',
    lastName: 'Wilson',
    email: 'ella.wilson@emp.com',
    hireDate: new Date('2020-05-30'),
    dismissalDate: null,
    department: 'finance',
    salary: 80000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '42',
    firstName: 'Jackson',
    lastName: 'Davis',
    email: 'jackson.davis@emp.com',
    hireDate: new Date('2023-06-15'),
    dismissalDate: null,
    department: 'engineering',
    salary: 85000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '43',
    firstName: 'Penelope',
    lastName: 'Anderson',
    email: 'penelope.anderson@emp.com',
    hireDate: new Date('2023-07-20'),
    dismissalDate: null,
    department: 'finance',
    salary: 90000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '44',
    firstName: 'Leo',
    lastName: 'Martinez',
    email: 'leo.martinez@emp.com',
    hireDate: new Date('2020-08-10'),
    dismissalDate: null,
    department: 'customer success',
    salary: 95000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '45',
    firstName: 'Stella',
    lastName: 'Taylor',
    email: 'stella.taylor@emp.com',
    hireDate: new Date('2023-09-25'),
    dismissalDate: null,
    department: 'engineering',
    salary: 100000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'superadmin',
  },
  {
    id: '46',
    firstName: 'Lucas',
    lastName: 'Brown',
    email: 'lucas.brown@emp.com',
    hireDate: new Date('2023-10-30'),
    dismissalDate: null,
    department: 'finance',
    salary: 105000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '47',
    firstName: 'Harper',
    lastName: 'Johnson',
    email: 'harper.johnson@emp.com',
    hireDate: new Date('2018-11-15'),
    dismissalDate: null,
    department: 'engineering',
    salary: 110000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '48',
    firstName: 'Jackson',
    lastName: 'Davis',
    email: 'jackson.davis@emp.com',
    hireDate: new Date('2023-12-20'),
    dismissalDate: null,
    department: 'finance',
    salary: 115000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '49',
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma.wilson@emp.com',
    hireDate: new Date('2019-01-05'),
    dismissalDate: null,
    department: 'engineering',
    salary: 120000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '50',
    firstName: 'Liam',
    lastName: 'Davis',
    email: 'liam.davis@emp.com',
    hireDate: new Date('2024-02-10'),
    dismissalDate: null,
    department: 'finance',
    salary: 125000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '51',
    firstName: 'Olivia',
    lastName: 'Johnson',
    email: 'olivia.johnson@emp.com',
    hireDate: new Date('2024-03-15'),
    dismissalDate: null,
    department: 'engineering',
    salary: 130000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '52',
    firstName: 'Ethan',
    lastName: 'Brown',
    email: 'ethan.brown@emp.com',
    hireDate: new Date('2024-04-20'),
    dismissalDate: null,
    department: 'finance',
    salary: 135000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '53',
    firstName: 'Ava',
    lastName: 'Wilson',
    email: 'ava.wilson@emp.com',
    hireDate: new Date('2024-05-10'),
    dismissalDate: null,
    department: 'customer success',
    salary: 140000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '54',
    firstName: 'Mason',
    lastName: 'Davis',
    email: 'mason.davis@emp.com',
    hireDate: new Date('2024-06-25'),
    dismissalDate: null,
    department: 'engineering',
    salary: 145000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'superadmin',
  },
  {
    id: '55',
    firstName: 'Isabella',
    lastName: 'Johnson',
    email: 'isabella.johnson@emp.com',
    hireDate: new Date('2024-07-20'),
    dismissalDate: null,
    department: 'finance',
    salary: 150000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '56',
    firstName: 'James',
    lastName: 'Brown',
    email: 'james.brown@emp.com',
    hireDate: new Date('2024-08-15'),
    dismissalDate: null,
    department: 'engineering',
    salary: 155000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '57',
    firstName: 'Emily',
    lastName: 'Wilson',
    email: 'emily.wilson@emp.com',
    hireDate: new Date('2020-09-10'),
    dismissalDate: null,
    department: 'finance',
    salary: 160000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  },
  {
    id: '58',
    firstName: 'Benjamin',
    lastName: 'Davis',
    email: 'benjamin.davis@emp.com',
    hireDate: new Date('2021-10-05'),
    dismissalDate: null,
    department: 'customer success',
    salary: 165000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'user',
  },
  {
    id: '59',
    firstName: 'Charlotte',
    lastName: 'Johnson',
    email: 'charlotte.johnson@emp.com',
    hireDate: new Date('2022-11-30'),
    dismissalDate: null,
    department: 'engineering',
    salary: 170000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'superadmin',
  },
  {
    id: '60',
    firstName: 'Henry',
    lastName: 'Brown',
    email: 'henry.brown@emp.com',
    hireDate: new Date('2023-12-25'),
    dismissalDate: null,
    department: 'finance',
    salary: 175000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '61',
    firstName: 'Sophia',
    lastName: 'Johnson',
    email: 'sophia.johnson@emp.com',
    hireDate: new Date('2021-01-01'),
    dismissalDate: null,
    department: 'engineering',
    salary: 180000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '62',
    firstName: 'William',
    lastName: 'Davis',
    email: 'william.davis@emp.com',
    hireDate: new Date('2021-02-05'),
    dismissalDate: null,
    department: 'finance',
    salary: 185000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'admin',
  },
  {
    id: '63',
    firstName: 'Olivia',
    lastName: 'Wilson',
    email: 'olivia.wilson@emp.com',
    hireDate: new Date('2021-03-10'),
    dismissalDate: null,
    department: 'customer success',
    salary: 190000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'user',
  },
  {
    id: '64',
    firstName: 'Liam',
    lastName: 'Brown',
    email: 'liam.brown@emp.com',
    hireDate: new Date('2021-04-15'),
    dismissalDate: null,
    department: 'engineering',
    salary: 195000,
    picture: '/backend/src/assets/profile2.jpg',
    role: 'superadmin',
  },
  {
    id: '65',
    firstName: 'Emma',
    lastName: 'Davis',
    email: 'emma.davis@emp.com',
    hireDate: new Date('2021-05-20'),
    dismissalDate: null,
    department: 'finance',
    salary: 200000,
    picture: '/backend/src/assets/profile1.jpg',
    role: 'admin',
  }
];

const initializeEmployees = async () => {
    try {
      await Employee.bulkCreate(defaultEmployees, { ignoreDuplicates: true });
    } catch (error) {
      console.error('Error initializing employees:', error);
    }
  };
  
  export default initializeEmployees;